blank_issues_enabled: false
contact_links:
  - name: New data entries
    url: https://github.community/
    about: Please suggest here new or refined types of stored data
  - name: Tracking issue
    about: Use this template for tracking new features.
    title: "[DATE]: [FEATURE NAME]"
    labels: tracking issue, needs triage
    url: http://www.pygran.org
